local module = require(script.Parent.Parent:FindFirstChild("jsdotlua_pretty-format@3.10.0"):FindFirstChild("pretty-format"))
export type Colors  = module.Colors 
export type CompareKeys  = module.CompareKeys 
export type Config  = module.Config 
export type Options  = module.Options 
export type OptionsReceived  = module.OptionsReceived 
export type OldPlugin  = module.OldPlugin 
export type NewPlugin  = module.NewPlugin 
export type Plugin  = module.Plugin 
export type Plugins  = module.Plugins 
export type PrettyFormatOptions  = module.PrettyFormatOptions 
export type Printer  = module.Printer 
export type Refs  = module.Refs 
export type Theme  = module.Theme 
return module