local module = require(script.Parent.Parent:FindFirstChild("jsdotlua_jest-reporters@3.10.0"):FindFirstChild("jest-reporters"))
export type BaseReporter  = module.BaseReporter 
export type DefaultReporter  = module.DefaultReporter 
export type SummaryReporter  = module.SummaryReporter 
export type VerboseReporter  = module.VerboseReporter 
export type Context  = module.Context 
export type Reporter  = module.Reporter 
export type ReporterOnStartOptions  = module.ReporterOnStartOptions 
export type ReporterContext  = module.ReporterContext 
export type SummaryOptions  = module.SummaryOptions 
export type Test  = module.Test 
return module