local module = require(script.Parent.Parent:FindFirstChild("jsdotlua_jest-console@3.10.0"):FindFirstChild("jest-console"))
export type Console  = module.Console 
export type ConsoleOptions  = module.ConsoleOptions 
export type BufferedConsole  = module.BufferedConsole 
export type CustomConsole  = module.CustomConsole 
export type NullConsole  = module.NullConsole 
export type ConsoleBuffer  = module.ConsoleBuffer 
export type LogMessage  = module.LogMessage 
export type LogType  = module.LogType 
export type LogEntry  = module.LogEntry 
export type InspectOptions  = module.InspectOptions 
return module