local module = require(script.Parent.Parent:FindFirstChild("jsdotlua_jest-mock-genv@3.10.0"):FindFirstChild("jest-mock-genv"))
export type GlobalAutomockFn  = module.GlobalAutomockFn 
export type GlobalAutomocks  = module.GlobalAutomocks 
export type GlobalEnvLibrary  = module.GlobalEnvLibrary 
export type GlobalEnv  = module.GlobalEnv 
export type GlobalMocker  = module.GlobalMocker 
return module